import Footer from "@/components/landingPage/footer";
import Header from "@/components/landingPage/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={``}>

      <div>
        <Header/>
        {children}
        <Footer/>
      </div>
    </div>
  );
}